[launcher]
author = Compliance Control Plane
description = Modular compliance operations and evidence readiness for Splunk
version = 0.3.36

[package]
id = compliance_control_plane

[ui]
is_visible = 1
label = Compliance Control Plane

[id]
name = compliance_control_plane
version = 0.3.36

[install]
build = 1
is_configured = 0
